<?php 
return [
    'confirm' => 'Are You Sure?',
    'save_changes' => 'Save Changes',
    'error' => 'An error occurred, please reload the page',
    'validation_error' => 'Changes could not be updated, Some errors were found',
    'data_saved' => 'Changes successfully updated',
    'add_item' => 'Add Item',
    'remove' => 'Remove',
    'import' => 'Import',
    'download_data' => 'Download Data',
    'override_warning' => 'This will override your current settings. Are You Sure?',
    'image_url' => 'Image URL',
    'from_library' => 'From Library',
    'select' => 'Select',
    'search' => 'Search',
    'select_file' => 'Select file',
    'size' => 'Size',
    'line_height' => 'Line Height',
    'left' => 'Left',
    'right' => 'Right',
    'center' => 'Center',
    'justify' => 'Justify',
    'letter_spacing' => 'Letter Spacing',
    'word_spacing' => 'Word Spacing',
    'underline' => 'Underline',
    'italic' => 'Italic',
    'uppercase' => 'Uppercase',
    'settings' => 'Settings',
];